org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT
fabric_api_version=0.160.5+26.3
fabric_permission_api_version=1.0.8+fcdff87f02

mod_version=1.0.0-26.3
maven_group=dev.simke
archives_base_name=lodestone-warps
